Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [10]:
a_easy_input = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])

print(a_easy_input)

print("Размерность a_easy_input: {}".format(a_easy_input.ndim))

print("Форма a_easy_input: {}".format(a_easy_input.shape))

a = np.transpose(a_easy_input)

print(a)

print("Размерность a: {}".format(a.ndim))

print("Форма a: {}".format(a.shape))

mean_a = a.mean(axis=0)

print("среднее значение по каждому признаку (столбцу): {}".format(mean_a))


[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
Размерность a_easy_input: 2
Форма a_easy_input: (2, 5)
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность a: 2
Форма a: (5, 2)
среднее значение по каждому признаку (столбцу): [2.  8.4]


Задание 2
Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [14]:
a_centered = a - mean_a
print("массив a_centered:\n {}".format(a_centered))

массив a_centered:
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [22]:
a_row1 = a_centered[:,0].copy()
a_row2 = a_centered[:,1].copy()
print("Первый столбец: {}, второй столбец: {}".format(a_row1, a_row2))

a_centered_sp = a_row1.dot(a_row2)
print("Сколярное произведение двух столбцов: {}".format(a_centered_sp))
print("Сколярное произведение, деленное на число наблюдений (4): {}".format(a_centered_sp / 4))

Первый столбец: [-1.  0.  1.  1. -1.], второй столбец: [-2.4 -0.4  2.6  1.6 -1.4]
Сколярное произведение двух столбцов: 8.0
Сколярное произведение, деленное на число наблюдений (4): 2.0


* Задание 4
Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html
В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [30]:
print("Ковариационная матрица: \n {}".format(np.cov(a.T)))
print("Ковариация: {}". format(np.cov(a.T)[0,1]))

Ковариационная матрица: 
 [[1.  2. ]
 [2.  4.3]]
Ковариация: 2.0


доп материал: https://docs.scipy.org/doc/numpy-1.14.5/reference/generated/numpy.cov.html