1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно.

In [166]:
import numpy as np


In [167]:
a = np.array([i for i in range(12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [168]:
np.reshape(a, (2,6))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [169]:
np.reshape(a, (3,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [170]:
np.reshape(a, (4,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [171]:
np.reshape(a, (6,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [172]:
np.reshape(a, (12,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах — для обозначения числа столбцов, в двух — для строк).

In [173]:
np.reshape(a, (-1,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [174]:
np.reshape(a, (-1,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [175]:
np.reshape(a, (-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [176]:
np.reshape(a, (2,-1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [177]:
np.reshape(a, (3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

да (математически всегда, а в numpy вроде как не всегда https://stackoverflow.com/questions/773030/why-are-0d-arrays-in-numpy-not-considered-scalar и судя по задачке 6 может быть и 2 мерным)
??

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [178]:
import numpy.random as rand

numpy.random.standard_normal

numpy.random.standard_normal(size=None)
Draw samples from a standard Normal distribution (mean=0, stdev=1).

Parameters:	
size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
Returns:	
out : float or ndarray
Drawn samples.
https://docs.scipy.org/doc/numpy/reference/routines.random.html#distributions

In [179]:
m = np.array([[rand.standard_normal() for i in range(4)] for i in range(3)])
m

array([[ 1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112,  0.31424733]])

In [180]:
mm = np.reshape(m,(1,-1))
mm

array([[ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769,
        -0.46572975,  0.24196227, -1.91328024, -1.72491783, -0.56228753,
        -1.01283112,  0.31424733]])

In [181]:
print("size массива m: {}, массива mm: {}".format(m.size, mm.size))

size массива m: 12, массива mm: 12


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [196]:
a = np.array([i for i in range(20, 0, -2)])
print(a)


[20 18 16 14 12 10  8  6  4  2]


In [197]:
b = np.array([[j for i in range(1)] for j in range(20,1,-2)])
b


array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

разное число осей:

In [184]:
print("форма массива a: {}, массива b: {}".format(np.shape(a), np.shape(b)))
print("число осей (измерений) массива a: {}, массива b: {}".format(a.ndim, b.ndim)) 

форма массива a: (10,), массива b: (10, 1)
число осей (измерений) массива a: 1, массива b: 2


7. Вертикально соединить массивы a и b. a — двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [185]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [186]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [187]:
v = np.concatenate((a,b), axis=0)
print(v.size)
v

10


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [188]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [189]:
A = np.reshape(a,(4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [190]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [191]:
B = np.dot(A,At)
print(B)
print("Размер матрицы: ", B.shape)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы:  (4, 4)


In [192]:
if np.linalg.det(B) == 0:
    print("определитель равен нулю - обратной матрицы не существует")
else:
    print("обратная матрица", np.linalg.inv(a))

определитель равен нулю - обратной матрицы не существует


9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [193]:
rand.seed(42)
c = rand.randint(16, size=16)
print("\nМассив c:\n",c)
C = np.reshape(c,(4,-1))
print("\nМатрица C:\n", C)
D = B + C * 10
D_inv = np.linalg.inv(D)
print("\nМатрица D:\n{}\n\nОпределитель матрицы D:\n{}\n\nРанг матрицы D:\n{}\n\nОбратная матрицы D:\n{}".
      format(D, np.linalg.det(D), D.ndim, D_inv))


Массив c:
 [ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]

Матрица C:
 [[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]

Матрица D:
[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]

Определитель матрицы D:
-28511999.999999944

Ранг матрицы D:
2

Обратная матрицы D:
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные — к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C — в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [194]:
D_mask =D_inv.copy()
for i in range(4):
    for j in range(4):
        if D_inv[i][j] > 0:
            D_mask[i][j] = 1
        if D_inv[i][j] < 0:
            D_mask[i][j] = 0
print(D_mask)

[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]


In [195]:
E = np.where(D_mask > 0,B,C)
print("Матрица E:\n", E)
print("\nПроверка:\n Матрица B:\n{}\nМатрица C:\n{}".format(B,C))

Матрица E:
 [[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]

Проверка:
 Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица C:
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
